project_name: faktory_cron

release:
  github:
    owner: cdrx
    name: faktory_cron
  name_template: '{{.Tag}}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - typo
      - Merge pull request
      - Merge branch
      - '^refactor'

builds:
  - binary: faktory-cron
    main: .
    ldflags: -s -w -extldflags "-static" -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
    - LICENSE
    - README*
    - CHANGELOG*
    - crontab.yaml.sample
  replacements:
    darwin: macos

dockers:
  - image: cdrx/faktory-cron
    latest: true

#fpm:
#  bindir: /usr/local/bin

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
