faktory: tcp://localhost:7419
jobs:
  - job: test.one
    type: faktory
    schedule: "@every 5s"
    args:
      - 1
      - 2
    queue: default
    priority: 5
  - job: test.cron
    type: cron
    schedule: "@every 10s"
    args:
      - echo
      - Hello World
      - from GoLang
